app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/doc"
    
api:
    type: rest
    resource: "routing_api.yml" 
    
login:
    path:     /
    defaults: { _controller: AppBundle:Security:login }
    
login_check:
    path: /login_check
    
logout:
    path: /logout
    
homepage:
    path:     /home
    defaults: { _controller: AppBundle:Default:index }

register_user:
    path:     /user/new/
    defaults: { _controller: AppBundle:Security:register } 
    
new_product:
    path:     /products/new/
    defaults: { _controller: AppBundle:Product:createProduct } 
    
list_products:
    path:     /products/list/
    defaults: { _controller: AppBundle:Product:listProducts }    
    
edit_product:
    path:     /products/edit/{id}
    defaults: { _controller: AppBundle:Product:edit } 

delete_product_web:
    path:     /products/delete/{id}
    defaults: { _controller: AppBundle:Product:deleteProduct } 